<a href="https://colab.research.google.com/github/Tosin-doc/Tensorflow-in-10minutes/blob/main/Tensorflow_in_10minutes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

# Common Use Operations

In [2]:
#Making a constant tensor A, that does not change
A = tf.constant([[3, 2],
               [5, 2]])
#Making a Variable tensor VA, which can change. 
VA = tf.Variable([[3, 2],
                [5, 2]])
#Making another tensor B
B = tf.constant([[9, 5],
               [1, 3]])

In [3]:
#Concatenate columns
AB_concatenated = tf.concat(values=[A, B], axis=1)
print(('Adding B\'s columns to A:\n{0}').format(
AB_concatenated.numpy()
))

#Concatenate rows
AB_concatenated = tf.concat(values=[A, B], axis=0)
print(('\nAdding B\'s rows to A:\n{0}').format(
AB_concatenated.numpy()
))

Adding B's columns to A:
[[3 2 9 5]
 [5 2 1 3]]

Adding B's rows to A:
[[3 2]
 [5 2]
 [9 5]
 [1 3]]


In [4]:
#Making a tensor filled with zeros. shape=[rows, columns]
tensor = tf.zeros(shape=[3, 4], dtype=tf.int32)
print(('Tensor full of zeros as int32, 3 rows and 4 columns:\n{0}').format(
    tensor.numpy()
))

#Making a tensor filled with zeros with data type of float32
tensor = tf.ones(shape=[5, 3], dtype=tf.float32)
print(('Tensor full of ones as float32, 5 rows and 3 columns:\n{0}').format(
    tensor.numpy()
))

Tensor full of zeros as int32, 3 rows and 4 columns:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Tensor full of ones as float32, 5 rows and 3 columns:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [5]:
#Making a tensor for reshaping 
tensor = tf.constant([[3,2],
                     [5, 2],
                     [9, 5],
                     [1, 3]])
#Reshaping the tensor into a shape of: shape = [rows, columns]
reshaped_tensor = tf.reshape(tensor = tensor,
                            shape = [1, 8])

print(('Tensor BEFORE reshape:\n{0}').format(
    reshaped_tensor.numpy()
))

Tensor BEFORE reshape:
[[3 2 5 2 9 5 1 3]]


In [6]:
#Making a tensor
tensor = tf.constant([[3.1, 2.8],
                     [5.2, 2.3],
                     [9.7, 5.5],
                     [1.1, 3.4]],
                     dtype=tf.float32)
tensor_as_int = tf.cast(tensor, tf.int32)

print(('Tensor with floats:\n{0}').format(
    tensor.numpy()
))
print(('\nTensor cast from float to int (just remove the decimal, no rounding):\n{0}').format(
    tensor_as_int.numpy()
))

Tensor with floats:
[[3.1 2.8]
 [5.2 2.3]
 [9.7 5.5]
 [1.1 3.4]]

Tensor cast from float to int (just remove the decimal, no rounding):
[[3 2]
 [5 2]
 [9 5]
 [1 3]]


# Linear Algebra Operations

In [7]:
#Some Matrix A
A = tf.constant([[3, 7],
                [1, 9]])

A = tf.transpose(A)

print(('The transposed matrix A:\n{0}').format(
A
))

The transposed matrix A:
[[3 1]
 [7 9]]


In [8]:
#Some Matrix  A
A = tf.constant([[3, 7],
                [1, 9]])

#Some vector v
v = tf.constant([[5],
                [2]])

#Matrix Multiplication of A.v^T
Av = tf.matmul(A, v)

print(('Matrix Multiplication of A and v results in a new Tensor:\n{0}').format(
    Av
))

Matrix Multiplication of A and v results in a new Tensor:
[[29]
 [23]]


In [9]:
#Element-wise MUltiplication
Av = tf.multiply(A, v)

print(('Element-wise multiplication of A and v results in a new Tensor:\n{0}').format(
    Av
))

Element-wise multiplication of A and v results in a new Tensor:
[[15 35]
 [ 2 18]]


In [10]:
#Some Matrix A
A = tf.constant([[3, 7],
                [1, 9],
                [2, 5]])

#Get number of dimensions
rows, columns = A.shape
print(('Get rows and columns in tensor A:\n{0} rows\n{1} columns').format(
    rows, columns
))

#Making identity matrix
A_identity =  tf.eye(num_rows = rows,
                     num_columns = columns,
                     dtype = tf.int32)
print(('\nThe identity matrix of A:\n{0}').format(
    A_identity.numpy()
))

Get rows and columns in tensor A:
3 rows
2 columns

The identity matrix of A:
[[1 0]
 [0 1]
 [0 0]]


In [11]:
#Reusing  Matrix A
A = tf.constant([[3, 7],
                [1, 9]])

#Determinant must be: half, float32, float64, complex64, complex128
#Thus, we cast A to the data type float32
A = tf.dtypes.cast(A, tf.float32)

#Finding the determinant of A
det_A = tf.linalg.det(A)

print(('The determinant of A:\n{0}').format(
    det_A
))

The determinant of A:
20.000001907348633


In [12]:
#Defining a 3*3 matrix
A = tf.constant([[32, 83, 5],
                [17, 23, 10],
                [75, 39, 52]])

#Defining another 3*3 matrix
B = tf.constant([[28, 57, 20],
                [91, 10, 95],
                [37, 13, 45]])

#Finding the dot product
dot_AB = tf.tensordot(a=A, b=B, axes=1).numpy()

print(('Dot product of A.B^T results in a new Tensor:\n{0}').format(
    dot_AB
))

#Which is the same as matrix multiplication in this instance(axes=1)
AB = tf.matmul(A, B)

print(('\nMatrix Multiplication of A.B^T results in a new Tensor:\n{0}').format(
    AB
))

Dot product of A.B^T results in a new Tensor:
[[8634 2719 8750]
 [2939 1329 2975]
 [7573 5341 7545]]

Matrix Multiplication of A.B^T results in a new Tensor:
[[8634 2719 8750]
 [2939 1329 2975]
 [7573 5341 7545]]


# Calculating Gradients with Gradient Tape

In [13]:
import math

def gelu(x):
    return 0.5*x*(1+tf.tanh(tf.sqrt(2/math.pi)*(x+0.044715*tf.pow(x, 3))))

def get_gradient(x, activation_function):
    with tf.GradientTape() as gt:
        y = activation_function(x)
        
    gradient = gt.gradient(y, x).numpy()
    
    return gradient

x = tf.Variable(0.5)
gradient = get_gradient(x, gelu)

print('{0}  is the gradient of GELU with x={1}'.format(
    gradient, x.numpy()
))

0.8673698902130127  is the gradient of GELU with x=0.5


# Functions in TensorFlow with tf.function

In [14]:
import timeit
conv_layer = tf.keras.layers.Conv2D(100, 3)

@tf.function
def conv_fn(image):
    return conv_layer(image)

image = tf.zeros([1, 200, 200, 100])
#warm up
conv_layer(image); conv_fn(image)
    
no_tf_fn = timeit.timeit(lambda: conv_layer(image), number=10)
with_tf_fn = timeit.timeit(lambda: conv_fn(image), number=10)
difference = no_tf_fn - with_tf_fn

print("Without tf.function: ", no_tf_fn)
print("With tf.function: ", with_tf_fn)
print("Difference times a billion: ", difference)

Without tf.function:  0.0033828619998530485
With tf.function:  0.004586395999922388
Difference times a billion:  -0.0012035340000693395


# Custom Train and Test Functions for Neural Network

In [15]:
from __future__ import absolute_import, division, print_function, unicode_literals

from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model

tf.keras.backend.set_floatx('float64')

mnist = tf.keras.datasets.mnist

In [16]:
#Load Data & Remove color channels
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

#Add a channels dimension
x_train = x_train[..., tf.newaxis]
x_test = x_test[..., tf.newaxis]

train_ds = tf.data.Dataset.from_tensor_slices(
    (x_train, y_train)).shuffle(10000).batch(32)

test_ds = tf.data.Dataset.from_tensor_slices((x_test, y_test)).batch(32)

In [17]:
class MyModel(Model):
    def __init__(self,
                 loss_object,
                 optimizer,
                 train_loss,
                 train_metric,
                 test_loss,
                 test_metric):
    
           #Setting all the variables for our model.
        
        super(MyModel, self).__init__()
        self.conv1 = Conv2D(32, 3, activation='relu')
        self.flatten = Flatten()
        self.d1 = Dense(128, activation='relu')
        self.d1 = Dense(10, activation='softmax')
        
        self.loss_object = loss_object
        self.optimizer = optimizer
        self.train_loss = train_loss
        self.train_metric = train_metric
        self.test_loss = test_loss
        self.test_metric = test_metric

In [18]:
        def nn_model(self, x):
            '''
               Defining the architecture of our model. This is where we run
               through our whole dataset and return it, when training and 
               testing.
            '''
            
            x = self.conv1(x)
            x = self.flatten(x)
            x = self.d1(x)
            return self.d2(x)

In [19]:
@tf.function
def train_step(self, images, labels):
    '''
       This is a Tensorflow function, run once for each epoch for the
       whole input. We move forward first, then calculate gradients
       with Gradient Tape to move backwards.
    '''
    with tf.GradientTape() as tape:
        predictions = self.nn_model(images)
        loss = self.loss_object(labels, predictions)
    gradients = tape.gradient(loss, self.trainable_variables)
    optimizer.apply_gradients(zip(
                              gradients, self.trainable_variables))
    self.train_loss(loss)
    self.train_metric(labels, predictions)

In [20]:
@tf.function
def test_step(self, images, labels):
    '''
       This is a Tensorflow function, run once for each epoch for the
       whole input. 
    '''
    
    predictions = self.nn_model(images)
    t_loss = self.loss_object(labels, predictions)
        
    self.test_loss(t_loss)
    self.test_metric(labels, predictions)

In [21]:
def fit(self, train, test, epochs):
    '''
       This fit function runs training and testing.
    '''
    for epoch in range(epochs):
        for images, labels in train:
            self.train_step(images, labels)
        
        for test_images, test_labels in test:
            self.test_step(test_images, test_labels)
            
        template = 'Epoch {}, Loss: {}, Accuracy: {}, Test Loss: {}, Test Accurcay: {}'
        print(template.format(epoch+1,
                              self.train_loss.result(),
                              self.train_metric.result()*100,
                              self.test_loss.result(),
                              self.test_metric.result()*100))
        
        #Reset the metrics for the next epoch 
        self.train_loss.reset_states(),
        self.train_metric.reset_states(),
        self.test_loss.reset_states(),
        self.test_metric.reset_states()
        

In [22]:
#Make a loss object
loss_object = tf.keras.losses.SparseCategoricalCrossentropy()

#Select the optimizer
optimizer = tf.keras.optimizers.Adam()

#Specify the metrics for training
train_loss = tf.keras.metrics.Mean(name='train_loss')
train_metric = tf.keras.metrics.SparseCategoricalAccuracy(name='train_accuracy')

#Specify the metrics for testing
test_loss = tf.keras.metrics.Mean(name='test_loss')
test_metric = tf.keras.metrics.SparseCategoricalAccuracy(name='test_accuracy')


In [23]:
#Create an instance of the model
model = MyModel(loss_object = loss_object,
                optimizer = optimizer,
                train_loss = train_loss,
                train_metric = train_metric,
                test_loss = test_loss,
                test_metric = test_metric)

EPOCHS = 5

model.fit(train = train_ds,
          test = test_ds,
          epochs = EPOCHS)

TypeError: ignored